/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AdminAdminRouteRouteImport } from './routes/_admin/admin/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPlayerRouteRouteImport } from './routes/_app/_player/route'
import { Route as AppBigbangSandboxRouteImport } from './routes/_app/bigbang-sandbox'
import { Route as AppPromotionsRouteImport } from './routes/_app/promotions'
import { Route as AppVipRouteImport } from './routes/_app/vip'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest/reset-password'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AdminAdminActivityRouteImport } from './routes/_admin/admin/activity'
import { Route as AdminAdminBonusesRouteImport } from './routes/_admin/admin/bonuses'
import { Route as AdminAdminGamesRouteImport } from './routes/_admin/admin/games'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin/users'
import { Route as AdminAdminWithdrawalsRouteImport } from './routes/_admin/admin/withdrawals'
import { Route as AppPlayerBonusesRouteImport } from './routes/_app/_player/bonuses'
import { Route as AppPlayerHistoryRouteImport } from './routes/_app/_player/history'
import { Route as AppPlayerProfileRouteImport } from './routes/_app/_player/profile'
import { Route as AppPlayerWalletRouteImport } from './routes/_app/_player/wallet'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBigbangBalanceChangeRouteImport } from './routes/api/bigbang/balance-change'
import { Route as ApiBigbangUserDataRouteImport } from './routes/api/bigbang/user-data'
import { Route as ApiBigbangWebhookRouteImport } from './routes/api/bigbang/webhook'
import { Route as ApiDrakonKeyRouteImport } from './routes/api/drakon/$key'
import { Route as AppPlayerGamesGameIdRouteImport } from './routes/_app/_player/games/$gameId'
import { Route as ApiDrakonWebhookKeyDrakon_apiRouteImport } from './routes/api/drakon/webhook/$key/drakon_api'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRouteRoute = AdminAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlayerRouteRoute = AppPlayerRouteRouteImport.update({
  id: '/_player',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBigbangSandboxRoute = AppBigbangSandboxRouteImport.update({
  id: '/bigbang-sandbox',
  path: '/bigbang-sandbox',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPromotionsRoute = AppPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVipRoute = AppVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => AppRouteRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminActivityRoute = AdminAdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminBonusesRoute = AdminAdminBonusesRouteImport.update({
  id: '/bonuses',
  path: '/bonuses',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminGamesRoute = AdminAdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminWithdrawalsRoute = AdminAdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AppPlayerBonusesRoute = AppPlayerBonusesRouteImport.update({
  id: '/bonuses',
  path: '/bonuses',
  getParentRoute: () => AppPlayerRouteRoute,
} as any)
const AppPlayerHistoryRoute = AppPlayerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppPlayerRouteRoute,
} as any)
const AppPlayerProfileRoute = AppPlayerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppPlayerRouteRoute,
} as any)
const AppPlayerWalletRoute = AppPlayerWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppPlayerRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBigbangBalanceChangeRoute = ApiBigbangBalanceChangeRouteImport.update({
  id: '/api/bigbang/balance-change',
  path: '/api/bigbang/balance-change',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBigbangUserDataRoute = ApiBigbangUserDataRouteImport.update({
  id: '/api/bigbang/user-data',
  path: '/api/bigbang/user-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBigbangWebhookRoute = ApiBigbangWebhookRouteImport.update({
  id: '/api/bigbang/webhook',
  path: '/api/bigbang/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrakonKeyRoute = ApiDrakonKeyRouteImport.update({
  id: '/api/drakon/$key',
  path: '/api/drakon/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlayerGamesGameIdRoute = AppPlayerGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => AppPlayerRouteRoute,
} as any)
const ApiDrakonWebhookKeyDrakon_apiRoute =
  ApiDrakonWebhookKeyDrakon_apiRouteImport.update({
    id: '/api/drakon/webhook/$key/drakon_api',
    path: '/api/drakon/webhook/$key/drakon_api',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/bigbang-sandbox': typeof AppBigbangSandboxRoute
  '/promotions': typeof AppPromotionsRoute
  '/vip': typeof AppVipRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/admin/activity': typeof AdminAdminActivityRoute
  '/admin/bonuses': typeof AdminAdminBonusesRoute
  '/admin/games': typeof AdminAdminGamesRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/withdrawals': typeof AdminAdminWithdrawalsRoute
  '/bonuses': typeof AppPlayerBonusesRoute
  '/history': typeof AppPlayerHistoryRoute
  '/profile': typeof AppPlayerProfileRoute
  '/wallet': typeof AppPlayerWalletRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bigbang/balance-change': typeof ApiBigbangBalanceChangeRoute
  '/api/bigbang/user-data': typeof ApiBigbangUserDataRoute
  '/api/bigbang/webhook': typeof ApiBigbangWebhookRoute
  '/api/drakon/$key': typeof ApiDrakonKeyRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/games/$gameId': typeof AppPlayerGamesGameIdRoute
  '/api/drakon/webhook/$key/drakon_api': typeof ApiDrakonWebhookKeyDrakon_apiRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/bigbang-sandbox': typeof AppBigbangSandboxRoute
  '/promotions': typeof AppPromotionsRoute
  '/vip': typeof AppVipRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/admin/activity': typeof AdminAdminActivityRoute
  '/admin/bonuses': typeof AdminAdminBonusesRoute
  '/admin/games': typeof AdminAdminGamesRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/withdrawals': typeof AdminAdminWithdrawalsRoute
  '/bonuses': typeof AppPlayerBonusesRoute
  '/history': typeof AppPlayerHistoryRoute
  '/profile': typeof AppPlayerProfileRoute
  '/wallet': typeof AppPlayerWalletRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bigbang/balance-change': typeof ApiBigbangBalanceChangeRoute
  '/api/bigbang/user-data': typeof ApiBigbangUserDataRoute
  '/api/bigbang/webhook': typeof ApiBigbangWebhookRoute
  '/api/drakon/$key': typeof ApiDrakonKeyRoute
  '/admin': typeof AdminAdminIndexRoute
  '/games/$gameId': typeof AppPlayerGamesGameIdRoute
  '/api/drakon/webhook/$key/drakon_api': typeof ApiDrakonWebhookKeyDrakon_apiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_app': typeof AppRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_admin/admin': typeof AdminAdminRouteRouteWithChildren
  '/_app/_player': typeof AppPlayerRouteRouteWithChildren
  '/_app/bigbang-sandbox': typeof AppBigbangSandboxRoute
  '/_app/promotions': typeof AppPromotionsRoute
  '/_app/vip': typeof AppVipRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_app/': typeof AppIndexRoute
  '/_admin/admin/activity': typeof AdminAdminActivityRoute
  '/_admin/admin/bonuses': typeof AdminAdminBonusesRoute
  '/_admin/admin/games': typeof AdminAdminGamesRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_admin/admin/withdrawals': typeof AdminAdminWithdrawalsRoute
  '/_app/_player/bonuses': typeof AppPlayerBonusesRoute
  '/_app/_player/history': typeof AppPlayerHistoryRoute
  '/_app/_player/profile': typeof AppPlayerProfileRoute
  '/_app/_player/wallet': typeof AppPlayerWalletRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bigbang/balance-change': typeof ApiBigbangBalanceChangeRoute
  '/api/bigbang/user-data': typeof ApiBigbangUserDataRoute
  '/api/bigbang/webhook': typeof ApiBigbangWebhookRoute
  '/api/drakon/$key': typeof ApiDrakonKeyRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_app/_player/games/$gameId': typeof AppPlayerGamesGameIdRoute
  '/api/drakon/webhook/$key/drakon_api': typeof ApiDrakonWebhookKeyDrakon_apiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bigbang-sandbox'
    | '/promotions'
    | '/vip'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/activity'
    | '/admin/bonuses'
    | '/admin/games'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/bonuses'
    | '/history'
    | '/profile'
    | '/wallet'
    | '/api/auth/$'
    | '/api/bigbang/balance-change'
    | '/api/bigbang/user-data'
    | '/api/bigbang/webhook'
    | '/api/drakon/$key'
    | '/admin/'
    | '/games/$gameId'
    | '/api/drakon/webhook/$key/drakon_api'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bigbang-sandbox'
    | '/promotions'
    | '/vip'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/activity'
    | '/admin/bonuses'
    | '/admin/games'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/bonuses'
    | '/history'
    | '/profile'
    | '/wallet'
    | '/api/auth/$'
    | '/api/bigbang/balance-change'
    | '/api/bigbang/user-data'
    | '/api/bigbang/webhook'
    | '/api/drakon/$key'
    | '/admin'
    | '/games/$gameId'
    | '/api/drakon/webhook/$key/drakon_api'
  id:
    | '__root__'
    | '/_admin'
    | '/_app'
    | '/_guest'
    | '/_admin/admin'
    | '/_app/_player'
    | '/_app/bigbang-sandbox'
    | '/_app/promotions'
    | '/_app/vip'
    | '/_guest/forgot-password'
    | '/_guest/login'
    | '/_guest/register'
    | '/_guest/reset-password'
    | '/_app/'
    | '/_admin/admin/activity'
    | '/_admin/admin/bonuses'
    | '/_admin/admin/games'
    | '/_admin/admin/users'
    | '/_admin/admin/withdrawals'
    | '/_app/_player/bonuses'
    | '/_app/_player/history'
    | '/_app/_player/profile'
    | '/_app/_player/wallet'
    | '/api/auth/$'
    | '/api/bigbang/balance-change'
    | '/api/bigbang/user-data'
    | '/api/bigbang/webhook'
    | '/api/drakon/$key'
    | '/_admin/admin/'
    | '/_app/_player/games/$gameId'
    | '/api/drakon/webhook/$key/drakon_api'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBigbangBalanceChangeRoute: typeof ApiBigbangBalanceChangeRoute
  ApiBigbangUserDataRoute: typeof ApiBigbangUserDataRoute
  ApiBigbangWebhookRoute: typeof ApiBigbangWebhookRoute
  ApiDrakonKeyRoute: typeof ApiDrakonKeyRoute
  ApiDrakonWebhookKeyDrakon_apiRoute: typeof ApiDrakonWebhookKeyDrakon_apiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_player': {
      id: '/_app/_player'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppPlayerRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/bigbang-sandbox': {
      id: '/_app/bigbang-sandbox'
      path: '/bigbang-sandbox'
      fullPath: '/bigbang-sandbox'
      preLoaderRoute: typeof AppBigbangSandboxRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/promotions': {
      id: '/_app/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AppPromotionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/vip': {
      id: '/_app/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof AppVipRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/activity': {
      id: '/_admin/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminAdminActivityRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/bonuses': {
      id: '/_admin/admin/bonuses'
      path: '/bonuses'
      fullPath: '/admin/bonuses'
      preLoaderRoute: typeof AdminAdminBonusesRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/games': {
      id: '/_admin/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminAdminGamesRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_admin/admin/withdrawals': {
      id: '/_admin/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminAdminWithdrawalsRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/_app/_player/bonuses': {
      id: '/_app/_player/bonuses'
      path: '/bonuses'
      fullPath: '/bonuses'
      preLoaderRoute: typeof AppPlayerBonusesRouteImport
      parentRoute: typeof AppPlayerRouteRoute
    }
    '/_app/_player/history': {
      id: '/_app/_player/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppPlayerHistoryRouteImport
      parentRoute: typeof AppPlayerRouteRoute
    }
    '/_app/_player/profile': {
      id: '/_app/_player/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppPlayerProfileRouteImport
      parentRoute: typeof AppPlayerRouteRoute
    }
    '/_app/_player/wallet': {
      id: '/_app/_player/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppPlayerWalletRouteImport
      parentRoute: typeof AppPlayerRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bigbang/balance-change': {
      id: '/api/bigbang/balance-change'
      path: '/api/bigbang/balance-change'
      fullPath: '/api/bigbang/balance-change'
      preLoaderRoute: typeof ApiBigbangBalanceChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bigbang/user-data': {
      id: '/api/bigbang/user-data'
      path: '/api/bigbang/user-data'
      fullPath: '/api/bigbang/user-data'
      preLoaderRoute: typeof ApiBigbangUserDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bigbang/webhook': {
      id: '/api/bigbang/webhook'
      path: '/api/bigbang/webhook'
      fullPath: '/api/bigbang/webhook'
      preLoaderRoute: typeof ApiBigbangWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drakon/$key': {
      id: '/api/drakon/$key'
      path: '/api/drakon/$key'
      fullPath: '/api/drakon/$key'
      preLoaderRoute: typeof ApiDrakonKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_player/games/$gameId': {
      id: '/_app/_player/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AppPlayerGamesGameIdRouteImport
      parentRoute: typeof AppPlayerRouteRoute
    }
    '/api/drakon/webhook/$key/drakon_api': {
      id: '/api/drakon/webhook/$key/drakon_api'
      path: '/api/drakon/webhook/$key/drakon_api'
      fullPath: '/api/drakon/webhook/$key/drakon_api'
      preLoaderRoute: typeof ApiDrakonWebhookKeyDrakon_apiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAdminRouteRouteChildren {
  AdminAdminActivityRoute: typeof AdminAdminActivityRoute
  AdminAdminBonusesRoute: typeof AdminAdminBonusesRoute
  AdminAdminGamesRoute: typeof AdminAdminGamesRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminWithdrawalsRoute: typeof AdminAdminWithdrawalsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteRouteChildren: AdminAdminRouteRouteChildren = {
  AdminAdminActivityRoute: AdminAdminActivityRoute,
  AdminAdminBonusesRoute: AdminAdminBonusesRoute,
  AdminAdminGamesRoute: AdminAdminGamesRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminWithdrawalsRoute: AdminAdminWithdrawalsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteRouteWithChildren = AdminAdminRouteRoute._addFileChildren(
  AdminAdminRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminRouteRoute: typeof AdminAdminRouteRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRouteRoute: AdminAdminRouteRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppPlayerRouteRouteChildren {
  AppPlayerBonusesRoute: typeof AppPlayerBonusesRoute
  AppPlayerHistoryRoute: typeof AppPlayerHistoryRoute
  AppPlayerProfileRoute: typeof AppPlayerProfileRoute
  AppPlayerWalletRoute: typeof AppPlayerWalletRoute
  AppPlayerGamesGameIdRoute: typeof AppPlayerGamesGameIdRoute
}

const AppPlayerRouteRouteChildren: AppPlayerRouteRouteChildren = {
  AppPlayerBonusesRoute: AppPlayerBonusesRoute,
  AppPlayerHistoryRoute: AppPlayerHistoryRoute,
  AppPlayerProfileRoute: AppPlayerProfileRoute,
  AppPlayerWalletRoute: AppPlayerWalletRoute,
  AppPlayerGamesGameIdRoute: AppPlayerGamesGameIdRoute,
}

const AppPlayerRouteRouteWithChildren = AppPlayerRouteRoute._addFileChildren(
  AppPlayerRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppPlayerRouteRoute: typeof AppPlayerRouteRouteWithChildren
  AppBigbangSandboxRoute: typeof AppBigbangSandboxRoute
  AppPromotionsRoute: typeof AppPromotionsRoute
  AppVipRoute: typeof AppVipRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppPlayerRouteRoute: AppPlayerRouteRouteWithChildren,
  AppBigbangSandboxRoute: AppBigbangSandboxRoute,
  AppPromotionsRoute: AppPromotionsRoute,
  AppVipRoute: AppVipRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBigbangBalanceChangeRoute: ApiBigbangBalanceChangeRoute,
  ApiBigbangUserDataRoute: ApiBigbangUserDataRoute,
  ApiBigbangWebhookRoute: ApiBigbangWebhookRoute,
  ApiDrakonKeyRoute: ApiDrakonKeyRoute,
  ApiDrakonWebhookKeyDrakon_apiRoute: ApiDrakonWebhookKeyDrakon_apiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
